export const RULES = {
  REVIEW_MISSING: 10,

  SHIPPING_INFO_MISSING: 10,

  TRUST_BADGES_MISSING: 10,

  PRODUCT_OUT_OF_STOCK: 5,

  HERO_HEADING_MISSING: 15,

  META_DESCRIPTION_MISSING: 10,

  NO_COLLECTIONS: 15,

  FEW_PRODUCT_IMAGES: 15,

  NO_PRODUCT_VARIANTS: 10,
} as const;